### ISSUE TITLE
No game music

### ISSUE THREAD

**Issue by TeeeeSeeee** [alexmurray/space-cadet-pinball-snap#1]
I tried enabling the game music but to no effect.  So I started the game via terminal  snap run space-cadet-pinball and got the following:
SDL Error: Couldn't open /etc/timidity/freepats.cfg even though freepats is installed and the cfg is present.

Besides that the game runs perfectly and as a side note, thanks for porting.

**Comment by alexmurray** [comment]
Thanks for reporting this - it should hopefully be fixed in [162a457](https://github.com/alexmurray/space-cadet-pinball-snap/commit/162a45703c67fa4f75c2ed49589db4dd29d50dac) - the snap will rebuild automatically and get published to the edge channel - if you could wait a few hours and then try `sudo snap refresh --edge space-cadet-pinball` and let me know if that fixes the issue, that would be great. Cheers.

**Comment by TeeeeSeeee** [comment]
That fixes the issue.  Thanks again for the Port!
