### ISSUE TITLE
License is not correct

### ISSUE THREAD

**Issue by Ma5t3rful** [alexmurray/space-cadet-pinball-snap#2]
The [store](https://snapcraft.io/space-cadet-pinball) shows it's proprietary but the [source code](https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/LICENSE) is licensed under MIT.

**Comment by alexmurray** [comment]
I highly doubt that Microsoft licensed the original source code as MIT - so I am not sure it is right to say that a reverse-engineered version, generated from decompiling the original binaries can then be licensed as MIT. Therefore, to err on the side of caution, I am declaring the license of the snap as Proprietary.

**Comment by alexmurray** [comment]
Also the snap includes other assets like https://archive.org/download/SpaceCadet_Plus95/ which is licensed under public domain - as such declaring the overall license then as MIT would not be accurate, so for now I feel it is better to keep it as Proprietary (since as far as I know, it is not possible to declare multiple licenses for a snap).

**Comment by Ma5t3rful** [comment]
The main devs put their software in [flathub](https://flathub.org/apps/com.github.k4zmu2a.spacecadetpinball) as an MIT-licensed. I agree with your points tho.
